test: upload coverage even if test failed

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -18,12 +18,9 @@ jobs:
       run: npx webpack --config-name=coverage
     - name: Run tests and generate coverage with mocha and nyc
       run: xvfb-run --auto-servernum npm run coverage
-    # - name: Upload coverage to Coveralls
-    #   uses: coverallsapp/github-action@master
-    #   with:
-    #     github-token: ${{ secrets.GITHUB_TOKEN }}
     - name: Upload coverage to Codecov.io
       uses: codecov/codecov-action@v1
+      if: succeeded() || failed() # upload even if test failed
       with:
         file: ./coverage/lcov.info # generated by nyc
         # flags: unittests # optional
